apiVersion: v1
kind: Service
metadata:
        name: psweb
spec:
    selector:
            env: develop
            projet: devops-training
    type: NodePort
    ports:
    - port: 8090
      targetPort: 8090
      nodePort: 31001
